### ISSUE TITLE
Cannot convert undefined or null to object when search my username

### ISSUE THREAD

**Issue by AsgoreChara666** [SkyCryptWebsite/SkyCrypt#1959]
**Describe the bug**
Cannot convert undefined or null to object when search my username

**Profile/Location**
https://sky.shiiyu.moe/stats/garefs

**Expected behavior**
can get in and check my profile

**Screenshots**
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/66071366/4078fdca-2ac8-4af8-8d97-5ddc7f809fa1)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 114.0.5735.134

**Smartphone (please complete the following information):**

- Device: iPhone 11
- OS: iOS 16.5
- Browser: Chrome
- Version: 114.0.5735.124

**Comment by metalcupcake5** [comment]
fixed in #1957

**Comment by AsgoreChara666** [comment]
![image](https://github.com/SkyCryptWebsite/SkyCrypt/assets/66071366/09f30093-3078-4fff-8650-d504672a024f)
still have this problem:|

**Comment by AsgoreChara666** [comment]
> fixed in #1957


![](https://user-images.githubusercontent.com/66071366/247502733-09f30093-3078-4fff-8650-d504672a024f.png)
still have this problem:|
